### ISSUE TITLE
5E, PF2 - True RNG settings don't appear in Module Settings

### ISSUE THREAD

**Issue by apoapostolov** [kidfearless/Foundry-TrueRNG#1]
0.7.9, True RNG 1.0.1, with and without TidyUI, the Settings section for True RNG doesn't show up. 

P.S.: Found it, but the section is actually called General Module Settings, not the name of the mod itself. Is this intended?

![image](https://user-images.githubusercontent.com/4083812/114434998-52d11580-9bcc-11eb-8672-68c6477dc62e.png)

**Comment by RyamosThomas** [comment]
Originally it was going to be just the api key but I added a few other settings last second. 1.0.2 will have them in their own submenu for organization.

**Comment by apoapostolov** [comment]
This is still an issue in 1.0.2 - the section needs to be renamed from General Module Settings to True RNG

**Comment by RyamosThomas** [comment]
Yeah I need to research how submenus work more before I can add it.

**Comment by RyamosThomas** [comment]
Fixed in v1.0.3

**Comment by west1778** [comment]
I'm still having this issue and I'm on version v1.0.4 :(

**Comment by RyamosThomas** [comment]
> I'm still having this issue and I'm on version v1.0.4 :(

Try uninstalling and reinstalling the module. It may be that foundry was having issues replacing the files. Be sure to check that the folder is gone from your modules folder `C:\Users\YOUR_USERNAME\AppData\Local\FoundryVTT\Data\modules`

**Comment by RyamosThomas** [comment]
![image](https://user-images.githubusercontent.com/13614349/115127996-0739b580-9f98-11eb-88a8-a6496226318c.png)
I've done a clean install of the module installed from foundry directly to test it.

**Comment by west1778** [comment]
Well, I hadn't been using your module previously just installed it today at the current version so shouldn't have had any previous versions installed. I did uninstall and reinstall it but still isn't showing in the Module settings. 

Getting this error

![image](https://user-images.githubusercontent.com/73608023/115129016-0f9dea80-9fb0-11eb-9952-b0226927b5c7.png)

**Comment by west1778** [comment]
On a clean server running, it doesn't give me any errors and it shows up in the modules list so might be one of my many modules interfering with it.

**Comment by RyamosThomas** [comment]
> Well, I hadn't been using your module previously just installed it today at the current version so shouldn't have had any previous versions installed. I did uninstall and reinstall it but still isn't showing in the Module settings.
> 
> Getting this error
> 
> ![image](https://user-images.githubusercontent.com/73608023/115129016-0f9dea80-9fb0-11eb-9952-b0226927b5c7.png)

Should be fixed in v1.0.5, It appears the author of libwrapper decided to call the ready hook before the game was actually ready.

**Comment by west1778** [comment]
:) Well, at least you know what's causing it right. :D LOL
